# Generated by Django 4.2.6 on 2023-10-10 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ico_name',
            field=models.CharField(default='none.png', max_length=16),
        ),
        migrations.AddField(
            model_name='operation',
            name='desctiption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='operation',
            name='short_description',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
